### ISSUE TITLE
Error loading collections MinimongoError: Duplicate _id

### ISSUE THREAD

**Issue by StorytellerCZ** [jamauro/offline#17]
Getting this when refreshing the page:
```
Error loading collections MinimongoError: Duplicate _id '9xGzRJM4TyBgRBaEx'
    at MinimongoError (common.js:1085:17)
    at LocalCollection.prepareInsert (local_collection.js:119:13)
    at LocalCollection.insert (local_collection.js:132:21)
    at loadAndObserve (load.js:23:23)
    at async Promise.all (index 51)
    at async load (load.js:64:5)
```
I have a context for the entire app which subscribes to the current user profiles collection which this is referring to (based on the ID).
I'm guessing that this data is there from previous session, so instead of insert, it should merge/update the data.

**Comment by jamauro** [comment]
Hmm, I haven't seen this in a while. If you can help with some minimal repro steps, I'd appreciate it.

**Comment by StorytellerCZ** [comment]
I'll see what I can do. I also think there might be a chance that the latest release might fix it. Will test today.

**Comment by harry-73** [comment]
I have the same issue on `Meteor 3.2 beta` but it was already the case before.

```
Error loading collections MinimongoError: Duplicate _id 'ObjectID("5bc0f407f12a79daea5dd82d")'
    at MinimongoError (common.js:1085:17)
    at LocalCollection.prepareInsert (local_collection.js:119:13)
    at LocalCollection.insert (local_collection.js:132:21)
    at loadAndObserve (load.js:28:23)
    at async Promise.all (activities/index 5)
    at async load (load.js:77:5)
```

It seems `users` minimongo collection is updated before `offline` package does its job:

![Image](https://github.com/user-attachments/assets/010dd43c-b34d-4ce6-91c7-a8ec61570ff1)

I do not subscribe to a publication based on `users` collection.

in `load.js` file, if I replace `localCollection.insert(doc);` by `localCollection.upsert(doc._id, doc);` the problem disappears.
